/*
 * The MIT License
 *
 * Copyright 2014 Andreas Giemza <andreas@giemza.net>.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package de.andreasgiemza.mangadownloader.gui.panels;

import de.andreasgiemza.mangadownloader.data.Chapter;
import de.andreasgiemza.mangadownloader.helpers.FilenameHelper;
import de.andreasgiemza.mangadownloader.data.Manga;
import de.andreasgiemza.mangadownloader.helpers.JsoupHelper;
import de.andreasgiemza.mangadownloader.sites.LINEWebtoon;
import de.andreasgiemza.mangadownloader.sites.Site;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

/**
 *
 * @author Andreas Giemza <andreas@giemza.net>
 */
public class Download extends javax.swing.JPanel {

    private volatile boolean interrupted;
    private final Path currentDirectory;
    private final Site site;
    private final Manga selectedManga;
    private final List<Chapter> chapters;
    private int chapterCount = 0;

    public Download(Path currentDirectory, Site site, Manga selectedManga, List<Chapter> chapters) {
        this.currentDirectory = currentDirectory;
        this.site = site;
        this.selectedManga = selectedManga;
        this.chapters = chapters;

        initComponents();

        // Setup manga info
        mangaTitleLabel.setText(selectedManga.getTitle());

        // Setup Chapter info
        for (Chapter chapter : chapters) {
            if (chapter.isDownload()) {
                chapterCount++;
            }
        }
        chapterProgressBar.setMaximum(chapterCount);
        chapterProgressBar.setString(0 + " of " + chapterCount);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mangaLabel = new javax.swing.JLabel();
        mangaTitleLabel = new javax.swing.JLabel();
        chapterLabel = new javax.swing.JLabel();
        chapterTileLabel = new javax.swing.JLabel();
        chapterProgressBar = new javax.swing.JProgressBar();
        imageLabel = new javax.swing.JLabel();
        imageProgressBar = new javax.swing.JProgressBar();
        startButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        errorLogPanel = new javax.swing.JPanel();
        errorLogScrollPane = new javax.swing.JScrollPane();
        errorLogTextArea = new javax.swing.JTextArea();

        mangaLabel.setText("Manga:");

        mangaTitleLabel.setText("TEMP");

        chapterLabel.setText("Chapter:");

        chapterTileLabel.setText(" ");

        chapterProgressBar.setString("");
        chapterProgressBar.setStringPainted(true);

        imageLabel.setText("Images:");

        imageProgressBar.setString("");
        imageProgressBar.setStringPainted(true);

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.setEnabled(false);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        errorLogPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Error Log"));

        errorLogTextArea.setEditable(false);
        errorLogTextArea.setColumns(20);
        errorLogTextArea.setRows(5);
        errorLogScrollPane.setViewportView(errorLogTextArea);

        javax.swing.GroupLayout errorLogPanelLayout = new javax.swing.GroupLayout(errorLogPanel);
        errorLogPanel.setLayout(errorLogPanelLayout);
        errorLogPanelLayout.setHorizontalGroup(
            errorLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(errorLogScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
        );
        errorLogPanelLayout.setVerticalGroup(
            errorLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(errorLogScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chapterProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imageProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(startButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(errorLogPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chapterLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(mangaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mangaTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chapterTileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mangaLabel)
                    .addComponent(mangaTitleLabel))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chapterLabel)
                    .addComponent(chapterTileLabel))
                .addGap(6, 6, 6)
                .addComponent(chapterProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(imageLabel)
                .addGap(6, 6, 6)
                .addComponent(imageProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(startButton)
                .addGap(11, 11, 11)
                .addComponent(cancelButton)
                .addGap(11, 11, 11)
                .addComponent(errorLogPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        startButton.setEnabled(false);
        cancelButton.setEnabled(true);

        interrupted = false;

        errorLogTextArea.setText("");
        new Thread(new Worker()).start();
    }//GEN-LAST:event_startButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        interrupted = true;
        cancelButton.setEnabled(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel chapterLabel;
    private javax.swing.JProgressBar chapterProgressBar;
    private javax.swing.JLabel chapterTileLabel;
    private javax.swing.JPanel errorLogPanel;
    private javax.swing.JScrollPane errorLogScrollPane;
    private javax.swing.JTextArea errorLogTextArea;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JProgressBar imageProgressBar;
    private javax.swing.JLabel mangaLabel;
    private javax.swing.JLabel mangaTitleLabel;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables

    private class Worker implements Runnable {

        private String errorLog = null;

        @Override
        public void run() {
            int chapterDone = 1;

            for (Chapter chapter : chapters) {
                if (chapter.isDownload()) {
                    if (interrupted) {
                        chapterError(currentDirectory, chapter, "Aborted while downloading: ");
                        updateGui();
                        return;
                    }

                    chapterTileLabel.setText(chapter.getTitle());
                    chapterProgressBar.setValue(chapterDone);
                    chapterProgressBar.setString(chapterDone + " of " + chapterCount);

                    imageProgressBar.setValue(0);
                    imageProgressBar.setString("Getting image links ...");

                    String mangaTitle = FilenameHelper.checkForIllegalCharacters(selectedManga.getTitle());
                    String chapterTitle = FilenameHelper.checkForIllegalCharacters(chapter.getTitle());

                    Path mangaFile = currentDirectory.resolve("mangas")
                            .resolve(mangaTitle)
                            .resolve(chapterTitle + ".cbz");

                    List<String> imageLinks;

                    try {
                        imageLinks = site.getChapterImageLinks(chapter);
                    } catch (IOException ex) {
                        chapterError(mangaFile, chapter, "Error while downloading: ");
                        continue;
                    }

                    imageProgressBar.setMaximum(imageLinks.size());

                    try {
                        if (!Files.exists(mangaFile.getParent())) {
                            Files.createDirectories(mangaFile.getParent());
                        }

                        if (Files.exists(mangaFile)) {
                            Files.delete(mangaFile);
                        }

                        try (ZipOutputStream zos = new ZipOutputStream(new FileOutputStream(mangaFile.toFile()))) {
                            for (int i = 0; i < imageLinks.size(); i++) {
                                if (interrupted) {
                                    zos.close();
                                    chapterError(mangaFile, chapter, "Aborted while downloading: ");
                                    updateGui();
                                    return;
                                }

                                imageProgressBar.setValue(i + 1);
                                imageProgressBar.setString((i + 1) + " of " + imageLinks.size());

                                String imageLink;
                                String extension;

                                if (site instanceof LINEWebtoon) {
                                    imageLink = imageLinks.get(i).split("\\?")[0];
                                    extension = imageLink.substring(imageLink.length() - 3, imageLink.length());
                                } else {
                                    imageLink = imageLinks.get(i);
                                    extension = imageLink.substring(imageLink.length() - 3, imageLink.length());
                                }

                                ZipEntry ze = new ZipEntry((i + 1) + "." + extension);
                                zos.putNextEntry(ze);

                                byte[] image;

                                if (site instanceof LINEWebtoon) {
                                    image = JsoupHelper.getImage(imageLink, chapter.getLink());
                                } else {
                                    image = JsoupHelper.getImage(imageLink);
                                }

                                zos.write(image, 0, image.length);
                                zos.closeEntry();
                            }
                        }
                    } catch (IOException ex) {
                        chapterError(mangaFile, chapter, "Error while downloading: ");
                        continue;
                    }

                    chapterDone++;
                }
            }

            updateGui();
        }

        private void updateGui() {
            startButton.setEnabled(true);
            cancelButton.setEnabled(false);
        }

        private void chapterError(Path mangaFile, Chapter chapter, String message) {
            if (Files.exists(mangaFile)) {
                try {
                    Files.delete(mangaFile);
                } catch (IOException ex) {
                }
            }

            if (errorLog == null) {
                errorLog = message + chapter.getTitle();
            } else {
                errorLog += "\n" + message + chapter.getTitle();
            }

            errorLogTextArea.setText(errorLog);
        }
    }
}
