/*
 * The MIT License
 *
 * Copyright 2014 Andreas Giemza <andreas@giemza.net>.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package de.andreasgiemza.mangadownloader.download;

import de.andreasgiemza.mangadownloader.data.Chapter;
import de.andreasgiemza.mangadownloader.helpers.Filename;
import de.andreasgiemza.mangadownloader.data.Manga;
import de.andreasgiemza.mangadownloader.sites.Site;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;
import org.jsoup.Jsoup;

/**
 *
 * @author Andreas Giemza <andreas@giemza.net>
 */
public class Download extends javax.swing.JPanel {

    private volatile boolean interrupted;
    private final Path currentDirectory;
    private final Site site;
    private final Manga selectedManga;
    private final List<Chapter> chapters;
    private int chapterCount = 0;

    public Download(Path currentDirectory, Site site, Manga selectedManga, List<Chapter> chapters) {
        this.currentDirectory = currentDirectory;
        this.site = site;
        this.selectedManga = selectedManga;
        this.chapters = chapters;

        initComponents();

        // Setup manga info
        mangaTitleLabel.setText(selectedManga.getTitle());

        // Setup Chapter info
        for (Chapter chapter : chapters) {
            if (chapter.isDownload()) {
                chapterCount++;
            }
        }
        chapterProgressBar.setMaximum(chapterCount);
        chapterProgressBar.setString(0 + " of " + chapterCount);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mangaLabel = new javax.swing.JLabel();
        mangaTitleLabel = new javax.swing.JLabel();
        chapterLabel = new javax.swing.JLabel();
        chapterTileLabel = new javax.swing.JLabel();
        chapterProgressBar = new javax.swing.JProgressBar();
        imageLabel = new javax.swing.JLabel();
        imageProgressBar = new javax.swing.JProgressBar();
        startButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        mangaLabel.setText("Manga:");

        mangaTitleLabel.setText("TEMP");

        chapterLabel.setText("Chapter:");

        chapterTileLabel.setText(" ");

        chapterProgressBar.setString("");
        chapterProgressBar.setStringPainted(true);

        imageLabel.setText("Images:");

        imageProgressBar.setString("");
        imageProgressBar.setStringPainted(true);

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chapterProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imageProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(startButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(mangaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chapterLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mangaTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chapterTileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mangaLabel)
                    .addComponent(mangaTitleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chapterLabel)
                    .addComponent(chapterTileLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chapterProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imageProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(startButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        startButton.setEnabled(false);
        cancelButton.setEnabled(true);

        interrupted = false;

        new Thread(new Worker()).start();
    }//GEN-LAST:event_startButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel chapterLabel;
    private javax.swing.JProgressBar chapterProgressBar;
    private javax.swing.JLabel chapterTileLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JProgressBar imageProgressBar;
    private javax.swing.JLabel mangaLabel;
    private javax.swing.JLabel mangaTitleLabel;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables

    private class Worker implements Runnable {

        @Override
        public void run() {
            int chapterDone = 1;

            for (Chapter chapter : chapters) {
                if (interrupted) {
                    updateGui();
                    return;
                }

                if (chapter.isDownload()) {
                    chapterTileLabel.setText(chapter.getTitle());
                    chapterProgressBar.setValue(chapterDone);
                    chapterProgressBar.setString(chapterDone + " of " + chapterCount);

                    imageProgressBar.setValue(0);
                    imageProgressBar.setString("Getting image links ...");
                    List<String> imageLinks = site.getChapterImageLinks(chapter);
                    imageProgressBar.setMaximum(imageLinks.size());

                    String mangaTitle = Filename.checkForIllegalCharacters(selectedManga.getTitle());
                    String chapterTitle = Filename.checkForIllegalCharacters(chapter.getTitle());

                    Path mangaFile = currentDirectory.resolve("mangas")
                            .resolve(mangaTitle)
                            .resolve(chapterTitle + ".cbz");

                    try {
                        if (!Files.exists(mangaFile.getParent())) {
                            Files.createDirectories(mangaFile.getParent());
                        }

                        if (Files.exists(mangaFile)) {
                            Files.delete(mangaFile);
                        }

                        try (ZipOutputStream zos = new ZipOutputStream(new FileOutputStream(mangaFile.toFile()))) {
                            for (int i = 0; i < imageLinks.size(); i++) {
                                if (interrupted) {
                                    updateGui();
                                    return;
                                }

                                imageProgressBar.setValue(i + 1);
                                imageProgressBar.setString((i + 1) + " of " + imageLinks.size());

                                String imageLink = imageLinks.get(i);
                                String extension = imageLink.substring(imageLink.length() - 3, imageLink.length());

                                ZipEntry ze = new ZipEntry((i + 1) + "." + extension);
                                zos.putNextEntry(ze);

                                byte[] image = Jsoup.connect(imageLink)
                                        .maxBodySize(10 * 1024 * 1024)
                                        .userAgent("Mozilla/5.0 (Windows NT 6.3; rv:36.0) Gecko/20100101 Firefox/36.0")
                                        .ignoreContentType(true)
                                        .execute()
                                        .bodyAsBytes();

                                zos.write(image, 0, image.length);
                                zos.closeEntry();
                            }
                        }
                    } catch (IOException ex) {
                        Logger.getLogger(Download.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    chapterDone++;
                }
            }

            updateGui();
        }

        private void updateGui() {
            startButton.setEnabled(true);
            cancelButton.setEnabled(false);
        }
    }
}
