package de.andreasgiemza.mangadownloader.gui.dialogs;

import java.awt.Color;

/**
 *
 * @author Andreas Giemza <andreas@giemza.net>
 */
public class Loading extends javax.swing.JDialog {

    public Loading(java.awt.Frame parent, boolean modal, int x, int y, int width, int height) {
        super(parent, modal);
        initComponents();

        setBackground(new Color(0, 0, 0, 0));
        setLocation(x + (width / 2) - (getWidth() / 2), y + (height / 2) - (getHeight() / 2));
    }

    public void startRunnable(Runnable runnable) {
        new Thread(runnable).start();

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadingImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        loadingImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loading.gif"))); // NOI18N
        getContentPane().add(loadingImage);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel loadingImage;
    // End of variables declaration//GEN-END:variables
}
