package de.andreasgiemza.mangamanager.mangadetails;

import de.andreasgiemza.mangamanager.data.ChapterForSubscription;
import de.andreasgiemza.mangamanager.data.Subscription;

/**
 *
 * @author Andreas Giemza <andreas@giemza.net>
 */
public class MangaDetails extends javax.swing.JDialog {

    private final Subscription subscription;
    private final ChapterForSubscriptionTableModel chapterForSubscriptionTableModel;

    public MangaDetails(java.awt.Frame parent, boolean modal, Subscription subscription) {
        super(parent, modal);
        this.subscription = subscription;
        this.chapterForSubscriptionTableModel = new ChapterForSubscriptionTableModel(subscription.getChapters());
        initComponents();

        setLocation(parent.getX() + (parent.getWidth() / 2) - (getWidth() / 2),
                parent.getY() + (parent.getHeight() / 2) - (getHeight() / 2));

        setTitle(subscription.getSite().getName() + " - " + subscription.getManga().getTitle());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chaptersScrollPane = new javax.swing.JScrollPane();
        chaptersTable = new javax.swing.JTable();
        markReadButton = new javax.swing.JButton();
        markUnreadButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        chaptersTable.setModel(chapterForSubscriptionTableModel);
        chaptersScrollPane.setViewportView(chaptersTable);

        markReadButton.setText("Mark read");
        markReadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markReadButtonActionPerformed(evt);
            }
        });

        markUnreadButton.setText("Mark unread");

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chaptersScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(markReadButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(markUnreadButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chaptersScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(markReadButton)
                    .addComponent(markUnreadButton)
                    .addComponent(closeButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void markReadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markReadButtonActionPerformed
        for (int row : chaptersTable.getSelectedRows()) {
            ChapterForSubscription cfstm = ((ChapterForSubscriptionTableModel) chaptersTable.getModel()).getChapter(chaptersTable.convertRowIndexToModel(row));

            cfstm.setRead(ChapterForSubscription.READ);
        }

        chapterForSubscriptionTableModel.fireTableDataChanged();
    }//GEN-LAST:event_markReadButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane chaptersScrollPane;
    private javax.swing.JTable chaptersTable;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton markReadButton;
    private javax.swing.JButton markUnreadButton;
    // End of variables declaration//GEN-END:variables
}
